Repository ModShardTeam/ModShardLauncher, pull requests merged in 2024-01, with the labels that each got.

#7 Slight improvements to the Documentation : how-to-play-mod.md
  .gitignore
  docs/guides/how-to-play-mod.md
Labels: documentation

#8 Documentation : Added Localization, last commit timestamp and author
  .github/workflows/ci.yml
  docs/guides/api.en.md
  docs/guides/api.zh.md
  docs/guides/how-to-play-mod.en.md
  docs/guides/how-to-play-mod.zh.md
  docs/guides/introduction.en.md
  docs/guides/introduction.zh.md
  docs/guides/start-modding-with-vsc.zh.md
  docs/guides/start-modding.en.md
  docs/guides/start-modding.zh.md
  docs/img/class_0.en.png
  docs/img/class_0.zh.png
  docs/img/class_1.en.png
  docs/img/compile_0.en.png
  docs/img/compile_1.en.png
  docs/img/create_project_0.en.png
  docs/img/create_project_0.zh.png
  docs/img/create_project_1.en.png
  docs/img/create_project_1.zh.png
  docs/img/create_project_2.en.png
  docs/img/create_project_2.zh.png
  docs/img/mod_0.en.png
  docs/img/mod_0.zh.png
  docs/img/mod_1.en.png
  docs/img/mod_1.zh.png
  docs/img/mod_2.en.png
  docs/img/mod_2.zh.png
  docs/img/mod_3.en.png
  docs/img/mod_3.zh.png
  docs/img/tool_UI.en.png
  docs/img/tool_UI2.en.png
  docs/img/tool_UI3.en.png
  docs/img/tool_UI4.en.png
  docs/img/tool_UI5.en.png
  docs/img/tool_UI6.en.png
  docs/img/weapon_0.en.png
  docs/img/weapon_0.zh.png
  docs/img/weapon_1.en.png
  docs/img/weapon_2.en.png
  docs/index.en.md
  docs/index.md
  docs/index.zh.md
  mkdocs.yml
Labels: documentation

#9 New api to mod with function chaining, name harmonization, moving stuff and fix warnings
  AssemblyWrapper.cs
  DataLoader.cs
  FileReader.cs
  ModLoader.cs
  ModLoaderUtils.cs
  ModShardLauncher.csproj
  ModShardLauncher.sln
  ModShardLauncherTest/GlobalUsings.cs
  ModShardLauncherTest/ModLoaderUtilsTest.cs
  ModShardLauncherTest/ModShardLauncherTest.csproj
  ModSources/SpeedShard/Codes/4xSpeed.gml
  ModSources/SpeedShard/Codes/LoadIni.gml
  ModSources/SpeedShard/Codes/QuickSave.gml
  ModSources/SpeedShard/SpeedShard.cs
  ModSources/SpeedShard/SpeedShard.csproj
  ModSources/SpeedShard/SpeedShard.sln
  ModSources/SpeedShard/icon.png
Labels: enhancement

#11 Mod loader improvement
  AssemblyWrapper.cs
  DataLoader.cs
  FileReader.cs
  Main.xaml.cs
  ModLoader.cs
  ModLoaderUtils.cs
  ModShardLauncher.csproj
  ModShardLauncher.sln
  ModShardLauncherTest/GlobalUsings.cs
  ModShardLauncherTest/ModLoaderUtilsTest.cs
  ModShardLauncherTest/ModShardLauncherTest.csproj
  ModSources/SpeedShard/Codes/4xSpeed.gml
  ModSources/SpeedShard/Codes/LoadIni.gml
  ModSources/SpeedShard/Codes/QuickSave.gml
  ModSources/SpeedShard/SpeedShard.cs
  ModSources/SpeedShard/SpeedShard.csproj
  ModSources/SpeedShard/SpeedShard.sln
  ModSources/SpeedShard/icon.png
Labels: documentation, enhancement

#12 Fixing dll-related build issues + Missing mod crash
  Main.xaml.cs
  ModReference/System.Collections.dll
  ModReference/System.Runtime.dll
  ModReference/netstandard.dll
  ModShardLauncher.csproj
Labels: enhancement

#13 Improving error handling
  DataLoader.cs
  FilePacker.cs
  FileReader.cs
  ModLoader.cs
  ModLoaderUtils.cs
  ModShardLauncher.csproj
  Mods/Weapon.cs
Labels: enhancement

#14 Wrote partial EN API Documentation
  README.md
  docs/guides/api.en.md
  mkdocs.yml
Labels: documentation

#15 Rewrote Modding Guide
  README.md
  docs/guides/how-to-play-mod.en.md
  docs/guides/start-modding.en.md
  docs/img/modding_codes.en.png
  docs/img/msl_template.en.png
  docs/img/msl_template_location.en.png
  mkdocs.yml
Labels: documentation

#19 Improving error handling
  DataLoader.cs
  FilePacker.cs
  FileReader.cs
  Main.xaml.cs
  ModLoader.cs
  ModLoaderUtils.cs
  Mods/ModSources.xaml.cs
  Mods/SourceBar.xaml.cs
  Pages/ModInfos.xaml.cs
Labels: enhancement

#22 Improved API navigation
  .gitignore
  docs/guides/api.en.md
  mkdocs.yml
Labels: documentation

#21 Testing texture integration
  DataLoader.cs
  FilePacker.cs
  FileReader.cs
  ModLoader.cs
  Mods/DisassemblyEditor.cs
  TextureLoader.cs
Labels: enhancement
