Repository ModShardTeam/ModShardLauncher, pull requests merged in 2024-04, with the labels that each got.

#50 Localization consum param
  ModShardLauncher.csproj
  ModShardLauncherTest/LocalizationUtilsTest.cs
  ModUtils/TableUtils.cs
  ModUtils/TableUtils/ConsumParam.cs
  ModUtils/TableUtils/LocalizationUtils.cs
  ModUtils/TableUtils/SkillsStat.cs
  ModUtils/TableUtils/TableUtils.cs
Labels: enhancement

#51 GetFile parsing unix-like path
  FileReader.cs
Labels: enhancement

#52 [Major] Removing auto load and save in settings and their dialog box aswell
  DataLoader.cs
  Main.xaml.cs
Labels: enhancement

#54 [Minor] sprite are correctly read + warning if empty file
  FileReader.cs
Labels: enhancement

#58 Updated issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: type:enhancement

#59 Table Injections
  .gitignore
  ModLoader.cs
  ModShardLauncher.csproj
  ModUtils/TableUtils/ConsumParam.cs
  ModUtils/TableUtils/Contract.cs
  ModUtils/TableUtils/CreditsBackers.cs
  ModUtils/TableUtils/EnemyBalance.cs
  ModUtils/TableUtils/Potion.cs
  ModUtils/TableUtils/SkillsStat.cs
  ModUtils/TableUtils/TableArmor.cs
  ModUtils/TableUtils/TableUtils.cs
  ModUtils/TableUtils/TableWeapons.cs
Labels: type:enhancement

#62 Fixes patching of non-vanilla `.win` files
  ModLoader.cs
Labels: state:pending, type:fix

#61 Mod menu
  Controls/ModInfos.xaml.cs
  DataLoader.cs
  ModLoader.cs
  ModUtils/LootUtils.cs
  ModUtils/ModMenuUtils.cs
Labels: type:enhancement, state:approved

#63 [Minor] change csproj version and fix disclaimer typo
  ModShardLauncher.csproj
  ModUtils/RoomUtils.cs
  future_workflow.md
Labels: type:enhancement

#66 Replaced System.Runtime.dll 8.0 with 6.0 version
  ModReference/System.Runtime.dll
  ModReference/netstandard.dll
Labels: priority:low, type:fix
